package io.github.yetyman.vulkan;

public interface VkStructureType {
    int VK_STRUCTURE_TYPE_APPLICATION_INFO = 0;
    int VK_STRUCTURE_TYPE_INSTANCE_CREATE_INFO = 1;
    int VK_STRUCTURE_TYPE_DEVICE_QUEUE_CREATE_INFO = 2;
    int VK_STRUCTURE_TYPE_DEVICE_CREATE_INFO = 3;
    int VK_STRUCTURE_TYPE_SUBMIT_INFO = 4;
    int VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO = 5;
    int VK_STRUCTURE_TYPE_COMMAND_BUFFER_ALLOCATE_INFO = 6;
    int VK_STRUCTURE_TYPE_COMMAND_BUFFER_BEGIN_INFO = 7;
    int VK_STRUCTURE_TYPE_BUFFER_CREATE_INFO = 12;
    int VK_STRUCTURE_TYPE_IMAGE_VIEW_CREATE_INFO = 14;
    int VK_STRUCTURE_TYPE_SHADER_MODULE_CREATE_INFO = 16;
    int VK_STRUCTURE_TYPE_COMMAND_POOL_CREATE_INFO = 39;
    int VK_STRUCTURE_TYPE_RENDER_PASS_CREATE_INFO = 38;
    int VK_STRUCTURE_TYPE_FRAMEBUFFER_CREATE_INFO = 37;
    int VK_STRUCTURE_TYPE_FENCE_CREATE_INFO = 8;
    int VK_STRUCTURE_TYPE_SEMAPHORE_CREATE_INFO = 9;
}
