package io.github.yetyman.glfw.enums;

import java.util.*;

/**
 * Type-safe constants for GLFWKey
 * Generated from jextract bindings
 */
public record GLFWKey(int value) {

    public static final GLFWKey GLFW_KEY_0 = new GLFWKey(48);
    public static final GLFWKey GLFW_KEY_1 = new GLFWKey(49);
    public static final GLFWKey GLFW_KEY_2 = new GLFWKey(50);
    public static final GLFWKey GLFW_KEY_3 = new GLFWKey(51);
    public static final GLFWKey GLFW_KEY_4 = new GLFWKey(52);
    public static final GLFWKey GLFW_KEY_5 = new GLFWKey(53);
    public static final GLFWKey GLFW_KEY_6 = new GLFWKey(54);
    public static final GLFWKey GLFW_KEY_7 = new GLFWKey(55);
    public static final GLFWKey GLFW_KEY_8 = new GLFWKey(56);
    public static final GLFWKey GLFW_KEY_9 = new GLFWKey(57);
    public static final GLFWKey GLFW_KEY_A = new GLFWKey(65);
    public static final GLFWKey GLFW_KEY_APOSTROPHE = new GLFWKey(39);
    public static final GLFWKey GLFW_KEY_B = new GLFWKey(66);
    public static final GLFWKey GLFW_KEY_BACKSLASH = new GLFWKey(92);
    public static final GLFWKey GLFW_KEY_BACKSPACE = new GLFWKey(259);
    public static final GLFWKey GLFW_KEY_C = new GLFWKey(67);
    public static final GLFWKey GLFW_KEY_CAPS_LOCK = new GLFWKey(280);
    public static final GLFWKey GLFW_KEY_COMMA = new GLFWKey(44);
    public static final GLFWKey GLFW_KEY_D = new GLFWKey(68);
    public static final GLFWKey GLFW_KEY_DELETE = new GLFWKey(261);
    public static final GLFWKey GLFW_KEY_DOWN = new GLFWKey(264);
    public static final GLFWKey GLFW_KEY_E = new GLFWKey(69);
    public static final GLFWKey GLFW_KEY_END = new GLFWKey(269);
    public static final GLFWKey GLFW_KEY_ENTER = new GLFWKey(257);
    public static final GLFWKey GLFW_KEY_EQUAL = new GLFWKey(61);
    public static final GLFWKey GLFW_KEY_ESCAPE = new GLFWKey(256);
    public static final GLFWKey GLFW_KEY_F = new GLFWKey(70);
    public static final GLFWKey GLFW_KEY_F1 = new GLFWKey(290);
    public static final GLFWKey GLFW_KEY_F10 = new GLFWKey(299);
    public static final GLFWKey GLFW_KEY_F11 = new GLFWKey(300);
    public static final GLFWKey GLFW_KEY_F12 = new GLFWKey(301);
    public static final GLFWKey GLFW_KEY_F13 = new GLFWKey(302);
    public static final GLFWKey GLFW_KEY_F14 = new GLFWKey(303);
    public static final GLFWKey GLFW_KEY_F15 = new GLFWKey(304);
    public static final GLFWKey GLFW_KEY_F16 = new GLFWKey(305);
    public static final GLFWKey GLFW_KEY_F17 = new GLFWKey(306);
    public static final GLFWKey GLFW_KEY_F18 = new GLFWKey(307);
    public static final GLFWKey GLFW_KEY_F19 = new GLFWKey(308);
    public static final GLFWKey GLFW_KEY_F2 = new GLFWKey(291);
    public static final GLFWKey GLFW_KEY_F20 = new GLFWKey(309);
    public static final GLFWKey GLFW_KEY_F21 = new GLFWKey(310);
    public static final GLFWKey GLFW_KEY_F22 = new GLFWKey(311);
    public static final GLFWKey GLFW_KEY_F23 = new GLFWKey(312);
    public static final GLFWKey GLFW_KEY_F24 = new GLFWKey(313);
    public static final GLFWKey GLFW_KEY_F25 = new GLFWKey(314);
    public static final GLFWKey GLFW_KEY_F3 = new GLFWKey(292);
    public static final GLFWKey GLFW_KEY_F4 = new GLFWKey(293);
    public static final GLFWKey GLFW_KEY_F5 = new GLFWKey(294);
    public static final GLFWKey GLFW_KEY_F6 = new GLFWKey(295);
    public static final GLFWKey GLFW_KEY_F7 = new GLFWKey(296);
    public static final GLFWKey GLFW_KEY_F8 = new GLFWKey(297);
    public static final GLFWKey GLFW_KEY_F9 = new GLFWKey(298);
    public static final GLFWKey GLFW_KEY_G = new GLFWKey(71);
    public static final GLFWKey GLFW_KEY_GRAVE_ACCENT = new GLFWKey(96);
    public static final GLFWKey GLFW_KEY_H = new GLFWKey(72);
    public static final GLFWKey GLFW_KEY_HOME = new GLFWKey(268);
    public static final GLFWKey GLFW_KEY_I = new GLFWKey(73);
    public static final GLFWKey GLFW_KEY_INSERT = new GLFWKey(260);
    public static final GLFWKey GLFW_KEY_J = new GLFWKey(74);
    public static final GLFWKey GLFW_KEY_K = new GLFWKey(75);
    public static final GLFWKey GLFW_KEY_KP_0 = new GLFWKey(320);
    public static final GLFWKey GLFW_KEY_KP_1 = new GLFWKey(321);
    public static final GLFWKey GLFW_KEY_KP_2 = new GLFWKey(322);
    public static final GLFWKey GLFW_KEY_KP_3 = new GLFWKey(323);
    public static final GLFWKey GLFW_KEY_KP_4 = new GLFWKey(324);
    public static final GLFWKey GLFW_KEY_KP_5 = new GLFWKey(325);
    public static final GLFWKey GLFW_KEY_KP_6 = new GLFWKey(326);
    public static final GLFWKey GLFW_KEY_KP_7 = new GLFWKey(327);
    public static final GLFWKey GLFW_KEY_KP_8 = new GLFWKey(328);
    public static final GLFWKey GLFW_KEY_KP_9 = new GLFWKey(329);
    public static final GLFWKey GLFW_KEY_KP_ADD = new GLFWKey(334);
    public static final GLFWKey GLFW_KEY_KP_DECIMAL = new GLFWKey(330);
    public static final GLFWKey GLFW_KEY_KP_DIVIDE = new GLFWKey(331);
    public static final GLFWKey GLFW_KEY_KP_ENTER = new GLFWKey(335);
    public static final GLFWKey GLFW_KEY_KP_EQUAL = new GLFWKey(336);
    public static final GLFWKey GLFW_KEY_KP_MULTIPLY = new GLFWKey(332);
    public static final GLFWKey GLFW_KEY_KP_SUBTRACT = new GLFWKey(333);
    public static final GLFWKey GLFW_KEY_L = new GLFWKey(76);
    public static final GLFWKey GLFW_KEY_LAST = new GLFWKey(348);
    public static final GLFWKey GLFW_KEY_LEFT = new GLFWKey(263);
    public static final GLFWKey GLFW_KEY_LEFT_ALT = new GLFWKey(342);
    public static final GLFWKey GLFW_KEY_LEFT_BRACKET = new GLFWKey(91);
    public static final GLFWKey GLFW_KEY_LEFT_CONTROL = new GLFWKey(341);
    public static final GLFWKey GLFW_KEY_LEFT_SHIFT = new GLFWKey(340);
    public static final GLFWKey GLFW_KEY_LEFT_SUPER = new GLFWKey(343);
    public static final GLFWKey GLFW_KEY_M = new GLFWKey(77);
    public static final GLFWKey GLFW_KEY_MENU = GLFW_KEY_LAST;
    public static final GLFWKey GLFW_KEY_MINUS = new GLFWKey(45);
    public static final GLFWKey GLFW_KEY_N = new GLFWKey(78);
    public static final GLFWKey GLFW_KEY_NUM_LOCK = new GLFWKey(282);
    public static final GLFWKey GLFW_KEY_O = new GLFWKey(79);
    public static final GLFWKey GLFW_KEY_P = new GLFWKey(80);
    public static final GLFWKey GLFW_KEY_PAGE_DOWN = new GLFWKey(267);
    public static final GLFWKey GLFW_KEY_PAGE_UP = new GLFWKey(266);
    public static final GLFWKey GLFW_KEY_PAUSE = new GLFWKey(284);
    public static final GLFWKey GLFW_KEY_PERIOD = new GLFWKey(46);
    public static final GLFWKey GLFW_KEY_PRINT_SCREEN = new GLFWKey(283);
    public static final GLFWKey GLFW_KEY_Q = new GLFWKey(81);
    public static final GLFWKey GLFW_KEY_R = new GLFWKey(82);
    public static final GLFWKey GLFW_KEY_RIGHT = new GLFWKey(262);
    public static final GLFWKey GLFW_KEY_RIGHT_ALT = new GLFWKey(346);
    public static final GLFWKey GLFW_KEY_RIGHT_BRACKET = new GLFWKey(93);
    public static final GLFWKey GLFW_KEY_RIGHT_CONTROL = new GLFWKey(345);
    public static final GLFWKey GLFW_KEY_RIGHT_SHIFT = new GLFWKey(344);
    public static final GLFWKey GLFW_KEY_RIGHT_SUPER = new GLFWKey(347);
    public static final GLFWKey GLFW_KEY_S = new GLFWKey(83);
    public static final GLFWKey GLFW_KEY_SCROLL_LOCK = new GLFWKey(281);
    public static final GLFWKey GLFW_KEY_SEMICOLON = new GLFWKey(59);
    public static final GLFWKey GLFW_KEY_SLASH = new GLFWKey(47);
    public static final GLFWKey GLFW_KEY_SPACE = new GLFWKey(32);
    public static final GLFWKey GLFW_KEY_T = new GLFWKey(84);
    public static final GLFWKey GLFW_KEY_TAB = new GLFWKey(258);
    public static final GLFWKey GLFW_KEY_U = new GLFWKey(85);
    public static final GLFWKey GLFW_KEY_UNKNOWN = new GLFWKey(-1);
    public static final GLFWKey GLFW_KEY_UP = new GLFWKey(265);
    public static final GLFWKey GLFW_KEY_V = new GLFWKey(86);
    public static final GLFWKey GLFW_KEY_W = new GLFWKey(87);
    public static final GLFWKey GLFW_KEY_WORLD_1 = new GLFWKey(161);
    public static final GLFWKey GLFW_KEY_WORLD_2 = new GLFWKey(162);
    public static final GLFWKey GLFW_KEY_X = new GLFWKey(88);
    public static final GLFWKey GLFW_KEY_Y = new GLFWKey(89);
    public static final GLFWKey GLFW_KEY_Z = new GLFWKey(90);

    public static GLFWKey fromValue(int value) {
        return switch (value) {
            case 48 -> GLFW_KEY_0;
            case 49 -> GLFW_KEY_1;
            case 50 -> GLFW_KEY_2;
            case 51 -> GLFW_KEY_3;
            case 52 -> GLFW_KEY_4;
            case 53 -> GLFW_KEY_5;
            case 54 -> GLFW_KEY_6;
            case 55 -> GLFW_KEY_7;
            case 56 -> GLFW_KEY_8;
            case 57 -> GLFW_KEY_9;
            case 65 -> GLFW_KEY_A;
            case 39 -> GLFW_KEY_APOSTROPHE;
            case 66 -> GLFW_KEY_B;
            case 92 -> GLFW_KEY_BACKSLASH;
            case 259 -> GLFW_KEY_BACKSPACE;
            case 67 -> GLFW_KEY_C;
            case 280 -> GLFW_KEY_CAPS_LOCK;
            case 44 -> GLFW_KEY_COMMA;
            case 68 -> GLFW_KEY_D;
            case 261 -> GLFW_KEY_DELETE;
            case 264 -> GLFW_KEY_DOWN;
            case 69 -> GLFW_KEY_E;
            case 269 -> GLFW_KEY_END;
            case 257 -> GLFW_KEY_ENTER;
            case 61 -> GLFW_KEY_EQUAL;
            case 256 -> GLFW_KEY_ESCAPE;
            case 70 -> GLFW_KEY_F;
            case 290 -> GLFW_KEY_F1;
            case 299 -> GLFW_KEY_F10;
            case 300 -> GLFW_KEY_F11;
            case 301 -> GLFW_KEY_F12;
            case 302 -> GLFW_KEY_F13;
            case 303 -> GLFW_KEY_F14;
            case 304 -> GLFW_KEY_F15;
            case 305 -> GLFW_KEY_F16;
            case 306 -> GLFW_KEY_F17;
            case 307 -> GLFW_KEY_F18;
            case 308 -> GLFW_KEY_F19;
            case 291 -> GLFW_KEY_F2;
            case 309 -> GLFW_KEY_F20;
            case 310 -> GLFW_KEY_F21;
            case 311 -> GLFW_KEY_F22;
            case 312 -> GLFW_KEY_F23;
            case 313 -> GLFW_KEY_F24;
            case 314 -> GLFW_KEY_F25;
            case 292 -> GLFW_KEY_F3;
            case 293 -> GLFW_KEY_F4;
            case 294 -> GLFW_KEY_F5;
            case 295 -> GLFW_KEY_F6;
            case 296 -> GLFW_KEY_F7;
            case 297 -> GLFW_KEY_F8;
            case 298 -> GLFW_KEY_F9;
            case 71 -> GLFW_KEY_G;
            case 96 -> GLFW_KEY_GRAVE_ACCENT;
            case 72 -> GLFW_KEY_H;
            case 268 -> GLFW_KEY_HOME;
            case 73 -> GLFW_KEY_I;
            case 260 -> GLFW_KEY_INSERT;
            case 74 -> GLFW_KEY_J;
            case 75 -> GLFW_KEY_K;
            case 320 -> GLFW_KEY_KP_0;
            case 321 -> GLFW_KEY_KP_1;
            case 322 -> GLFW_KEY_KP_2;
            case 323 -> GLFW_KEY_KP_3;
            case 324 -> GLFW_KEY_KP_4;
            case 325 -> GLFW_KEY_KP_5;
            case 326 -> GLFW_KEY_KP_6;
            case 327 -> GLFW_KEY_KP_7;
            case 328 -> GLFW_KEY_KP_8;
            case 329 -> GLFW_KEY_KP_9;
            case 334 -> GLFW_KEY_KP_ADD;
            case 330 -> GLFW_KEY_KP_DECIMAL;
            case 331 -> GLFW_KEY_KP_DIVIDE;
            case 335 -> GLFW_KEY_KP_ENTER;
            case 336 -> GLFW_KEY_KP_EQUAL;
            case 332 -> GLFW_KEY_KP_MULTIPLY;
            case 333 -> GLFW_KEY_KP_SUBTRACT;
            case 76 -> GLFW_KEY_L;
            case 348 -> GLFW_KEY_LAST;
            case 263 -> GLFW_KEY_LEFT;
            case 342 -> GLFW_KEY_LEFT_ALT;
            case 91 -> GLFW_KEY_LEFT_BRACKET;
            case 341 -> GLFW_KEY_LEFT_CONTROL;
            case 340 -> GLFW_KEY_LEFT_SHIFT;
            case 343 -> GLFW_KEY_LEFT_SUPER;
            case 77 -> GLFW_KEY_M;
            case 45 -> GLFW_KEY_MINUS;
            case 78 -> GLFW_KEY_N;
            case 282 -> GLFW_KEY_NUM_LOCK;
            case 79 -> GLFW_KEY_O;
            case 80 -> GLFW_KEY_P;
            case 267 -> GLFW_KEY_PAGE_DOWN;
            case 266 -> GLFW_KEY_PAGE_UP;
            case 284 -> GLFW_KEY_PAUSE;
            case 46 -> GLFW_KEY_PERIOD;
            case 283 -> GLFW_KEY_PRINT_SCREEN;
            case 81 -> GLFW_KEY_Q;
            case 82 -> GLFW_KEY_R;
            case 262 -> GLFW_KEY_RIGHT;
            case 346 -> GLFW_KEY_RIGHT_ALT;
            case 93 -> GLFW_KEY_RIGHT_BRACKET;
            case 345 -> GLFW_KEY_RIGHT_CONTROL;
            case 344 -> GLFW_KEY_RIGHT_SHIFT;
            case 347 -> GLFW_KEY_RIGHT_SUPER;
            case 83 -> GLFW_KEY_S;
            case 281 -> GLFW_KEY_SCROLL_LOCK;
            case 59 -> GLFW_KEY_SEMICOLON;
            case 47 -> GLFW_KEY_SLASH;
            case 32 -> GLFW_KEY_SPACE;
            case 84 -> GLFW_KEY_T;
            case 258 -> GLFW_KEY_TAB;
            case 85 -> GLFW_KEY_U;
            case -1 -> GLFW_KEY_UNKNOWN;
            case 265 -> GLFW_KEY_UP;
            case 86 -> GLFW_KEY_V;
            case 87 -> GLFW_KEY_W;
            case 161 -> GLFW_KEY_WORLD_1;
            case 162 -> GLFW_KEY_WORLD_2;
            case 88 -> GLFW_KEY_X;
            case 89 -> GLFW_KEY_Y;
            case 90 -> GLFW_KEY_Z;
            default -> new GLFWKey(value);
        };
    }
}
