package io.github.yetyman.vulkan.enums;

import java.util.*;

/**
 * Type-safe constants for VkDynamicState
 * Generated from jextract bindings
 */
public record VkDynamicState(int value) {

    public static final VkDynamicState VK_DYNAMIC_STATE_ALPHA_TO_COVERAGE_ENABLE_EXT = new VkDynamicState(1000455007);
    public static final VkDynamicState VK_DYNAMIC_STATE_ALPHA_TO_ONE_ENABLE_EXT = new VkDynamicState(1000455008);
    public static final VkDynamicState VK_DYNAMIC_STATE_ATTACHMENT_FEEDBACK_LOOP_ENABLE_EXT = new VkDynamicState(1000524000);
    public static final VkDynamicState VK_DYNAMIC_STATE_BLEND_CONSTANTS = new VkDynamicState(4);
    public static final VkDynamicState VK_DYNAMIC_STATE_COLOR_BLEND_ADVANCED_EXT = new VkDynamicState(1000455018);
    public static final VkDynamicState VK_DYNAMIC_STATE_COLOR_BLEND_ENABLE_EXT = new VkDynamicState(1000455010);
    public static final VkDynamicState VK_DYNAMIC_STATE_COLOR_BLEND_EQUATION_EXT = new VkDynamicState(1000455011);
    public static final VkDynamicState VK_DYNAMIC_STATE_COLOR_WRITE_ENABLE_EXT = new VkDynamicState(1000381000);
    public static final VkDynamicState VK_DYNAMIC_STATE_COLOR_WRITE_MASK_EXT = new VkDynamicState(1000455012);
    public static final VkDynamicState VK_DYNAMIC_STATE_CONSERVATIVE_RASTERIZATION_MODE_EXT = new VkDynamicState(1000455014);
    public static final VkDynamicState VK_DYNAMIC_STATE_COVERAGE_MODULATION_MODE_NV = new VkDynamicState(1000455027);
    public static final VkDynamicState VK_DYNAMIC_STATE_COVERAGE_MODULATION_TABLE_ENABLE_NV = new VkDynamicState(1000455028);
    public static final VkDynamicState VK_DYNAMIC_STATE_COVERAGE_MODULATION_TABLE_NV = new VkDynamicState(1000455029);
    public static final VkDynamicState VK_DYNAMIC_STATE_COVERAGE_REDUCTION_MODE_NV = new VkDynamicState(1000455032);
    public static final VkDynamicState VK_DYNAMIC_STATE_COVERAGE_TO_COLOR_ENABLE_NV = new VkDynamicState(1000455025);
    public static final VkDynamicState VK_DYNAMIC_STATE_COVERAGE_TO_COLOR_LOCATION_NV = new VkDynamicState(1000455026);
    public static final VkDynamicState VK_DYNAMIC_STATE_CULL_MODE = new VkDynamicState(1000267000);
    public static final VkDynamicState VK_DYNAMIC_STATE_CULL_MODE_EXT = VK_DYNAMIC_STATE_CULL_MODE;
    public static final VkDynamicState VK_DYNAMIC_STATE_DEPTH_BIAS = new VkDynamicState(3);
    public static final VkDynamicState VK_DYNAMIC_STATE_DEPTH_BIAS_ENABLE = new VkDynamicState(1000377002);
    public static final VkDynamicState VK_DYNAMIC_STATE_DEPTH_BIAS_ENABLE_EXT = VK_DYNAMIC_STATE_DEPTH_BIAS_ENABLE;
    public static final VkDynamicState VK_DYNAMIC_STATE_DEPTH_BOUNDS = new VkDynamicState(5);
    public static final VkDynamicState VK_DYNAMIC_STATE_DEPTH_BOUNDS_TEST_ENABLE = new VkDynamicState(1000267009);
    public static final VkDynamicState VK_DYNAMIC_STATE_DEPTH_BOUNDS_TEST_ENABLE_EXT = VK_DYNAMIC_STATE_DEPTH_BOUNDS_TEST_ENABLE;
    public static final VkDynamicState VK_DYNAMIC_STATE_DEPTH_CLAMP_ENABLE_EXT = new VkDynamicState(1000455003);
    public static final VkDynamicState VK_DYNAMIC_STATE_DEPTH_CLAMP_RANGE_EXT = new VkDynamicState(1000582000);
    public static final VkDynamicState VK_DYNAMIC_STATE_DEPTH_CLIP_ENABLE_EXT = new VkDynamicState(1000455016);
    public static final VkDynamicState VK_DYNAMIC_STATE_DEPTH_CLIP_NEGATIVE_ONE_TO_ONE_EXT = new VkDynamicState(1000455022);
    public static final VkDynamicState VK_DYNAMIC_STATE_DEPTH_COMPARE_OP = new VkDynamicState(1000267008);
    public static final VkDynamicState VK_DYNAMIC_STATE_DEPTH_COMPARE_OP_EXT = VK_DYNAMIC_STATE_DEPTH_COMPARE_OP;
    public static final VkDynamicState VK_DYNAMIC_STATE_DEPTH_TEST_ENABLE = new VkDynamicState(1000267006);
    public static final VkDynamicState VK_DYNAMIC_STATE_DEPTH_TEST_ENABLE_EXT = VK_DYNAMIC_STATE_DEPTH_TEST_ENABLE;
    public static final VkDynamicState VK_DYNAMIC_STATE_DEPTH_WRITE_ENABLE = new VkDynamicState(1000267007);
    public static final VkDynamicState VK_DYNAMIC_STATE_DEPTH_WRITE_ENABLE_EXT = VK_DYNAMIC_STATE_DEPTH_WRITE_ENABLE;
    public static final VkDynamicState VK_DYNAMIC_STATE_DISCARD_RECTANGLE_ENABLE_EXT = new VkDynamicState(1000099001);
    public static final VkDynamicState VK_DYNAMIC_STATE_DISCARD_RECTANGLE_EXT = new VkDynamicState(1000099000);
    public static final VkDynamicState VK_DYNAMIC_STATE_DISCARD_RECTANGLE_MODE_EXT = new VkDynamicState(1000099002);
    public static final VkDynamicState VK_DYNAMIC_STATE_EXCLUSIVE_SCISSOR_ENABLE_NV = new VkDynamicState(1000205000);
    public static final VkDynamicState VK_DYNAMIC_STATE_EXCLUSIVE_SCISSOR_NV = new VkDynamicState(1000205001);
    public static final VkDynamicState VK_DYNAMIC_STATE_EXTRA_PRIMITIVE_OVERESTIMATION_SIZE_EXT = new VkDynamicState(1000455015);
    public static final VkDynamicState VK_DYNAMIC_STATE_FRAGMENT_SHADING_RATE_KHR = new VkDynamicState(1000226000);
    public static final VkDynamicState VK_DYNAMIC_STATE_FRONT_FACE = new VkDynamicState(1000267001);
    public static final VkDynamicState VK_DYNAMIC_STATE_FRONT_FACE_EXT = VK_DYNAMIC_STATE_FRONT_FACE;
    public static final VkDynamicState VK_DYNAMIC_STATE_LINE_RASTERIZATION_MODE_EXT = new VkDynamicState(1000455020);
    public static final VkDynamicState VK_DYNAMIC_STATE_LINE_STIPPLE = new VkDynamicState(1000259000);
    public static final VkDynamicState VK_DYNAMIC_STATE_LINE_STIPPLE_ENABLE_EXT = new VkDynamicState(1000455021);
    public static final VkDynamicState VK_DYNAMIC_STATE_LINE_STIPPLE_EXT = VK_DYNAMIC_STATE_LINE_STIPPLE;
    public static final VkDynamicState VK_DYNAMIC_STATE_LINE_STIPPLE_KHR = VK_DYNAMIC_STATE_LINE_STIPPLE;
    public static final VkDynamicState VK_DYNAMIC_STATE_LINE_WIDTH = new VkDynamicState(2);
    public static final VkDynamicState VK_DYNAMIC_STATE_LOGIC_OP_ENABLE_EXT = new VkDynamicState(1000455009);
    public static final VkDynamicState VK_DYNAMIC_STATE_LOGIC_OP_EXT = new VkDynamicState(1000377003);
    public static final VkDynamicState VK_DYNAMIC_STATE_MAX_ENUM = new VkDynamicState(2147483647);
    public static final VkDynamicState VK_DYNAMIC_STATE_PATCH_CONTROL_POINTS_EXT = new VkDynamicState(1000377000);
    public static final VkDynamicState VK_DYNAMIC_STATE_POLYGON_MODE_EXT = new VkDynamicState(1000455004);
    public static final VkDynamicState VK_DYNAMIC_STATE_PRIMITIVE_RESTART_ENABLE = new VkDynamicState(1000377004);
    public static final VkDynamicState VK_DYNAMIC_STATE_PRIMITIVE_RESTART_ENABLE_EXT = VK_DYNAMIC_STATE_PRIMITIVE_RESTART_ENABLE;
    public static final VkDynamicState VK_DYNAMIC_STATE_PRIMITIVE_TOPOLOGY = new VkDynamicState(1000267002);
    public static final VkDynamicState VK_DYNAMIC_STATE_PRIMITIVE_TOPOLOGY_EXT = VK_DYNAMIC_STATE_PRIMITIVE_TOPOLOGY;
    public static final VkDynamicState VK_DYNAMIC_STATE_PROVOKING_VERTEX_MODE_EXT = new VkDynamicState(1000455019);
    public static final VkDynamicState VK_DYNAMIC_STATE_RASTERIZATION_SAMPLES_EXT = new VkDynamicState(1000455005);
    public static final VkDynamicState VK_DYNAMIC_STATE_RASTERIZATION_STREAM_EXT = new VkDynamicState(1000455013);
    public static final VkDynamicState VK_DYNAMIC_STATE_RASTERIZER_DISCARD_ENABLE = new VkDynamicState(1000377001);
    public static final VkDynamicState VK_DYNAMIC_STATE_RASTERIZER_DISCARD_ENABLE_EXT = VK_DYNAMIC_STATE_RASTERIZER_DISCARD_ENABLE;
    public static final VkDynamicState VK_DYNAMIC_STATE_RAY_TRACING_PIPELINE_STACK_SIZE_KHR = new VkDynamicState(1000347000);
    public static final VkDynamicState VK_DYNAMIC_STATE_REPRESENTATIVE_FRAGMENT_TEST_ENABLE_NV = new VkDynamicState(1000455031);
    public static final VkDynamicState VK_DYNAMIC_STATE_SAMPLE_LOCATIONS_ENABLE_EXT = new VkDynamicState(1000455017);
    public static final VkDynamicState VK_DYNAMIC_STATE_SAMPLE_LOCATIONS_EXT = new VkDynamicState(1000143000);
    public static final VkDynamicState VK_DYNAMIC_STATE_SAMPLE_MASK_EXT = new VkDynamicState(1000455006);
    public static final VkDynamicState VK_DYNAMIC_STATE_SCISSOR = new VkDynamicState(1);
    public static final VkDynamicState VK_DYNAMIC_STATE_SCISSOR_WITH_COUNT = new VkDynamicState(1000267004);
    public static final VkDynamicState VK_DYNAMIC_STATE_SCISSOR_WITH_COUNT_EXT = VK_DYNAMIC_STATE_SCISSOR_WITH_COUNT;
    public static final VkDynamicState VK_DYNAMIC_STATE_SHADING_RATE_IMAGE_ENABLE_NV = new VkDynamicState(1000455030);
    public static final VkDynamicState VK_DYNAMIC_STATE_STENCIL_COMPARE_MASK = new VkDynamicState(6);
    public static final VkDynamicState VK_DYNAMIC_STATE_STENCIL_OP = new VkDynamicState(1000267011);
    public static final VkDynamicState VK_DYNAMIC_STATE_STENCIL_OP_EXT = VK_DYNAMIC_STATE_STENCIL_OP;
    public static final VkDynamicState VK_DYNAMIC_STATE_STENCIL_REFERENCE = new VkDynamicState(8);
    public static final VkDynamicState VK_DYNAMIC_STATE_STENCIL_TEST_ENABLE = new VkDynamicState(1000267010);
    public static final VkDynamicState VK_DYNAMIC_STATE_STENCIL_TEST_ENABLE_EXT = VK_DYNAMIC_STATE_STENCIL_TEST_ENABLE;
    public static final VkDynamicState VK_DYNAMIC_STATE_STENCIL_WRITE_MASK = new VkDynamicState(7);
    public static final VkDynamicState VK_DYNAMIC_STATE_TESSELLATION_DOMAIN_ORIGIN_EXT = new VkDynamicState(1000455002);
    public static final VkDynamicState VK_DYNAMIC_STATE_VERTEX_INPUT_BINDING_STRIDE = new VkDynamicState(1000267005);
    public static final VkDynamicState VK_DYNAMIC_STATE_VERTEX_INPUT_BINDING_STRIDE_EXT = VK_DYNAMIC_STATE_VERTEX_INPUT_BINDING_STRIDE;
    public static final VkDynamicState VK_DYNAMIC_STATE_VERTEX_INPUT_EXT = new VkDynamicState(1000352000);
    public static final VkDynamicState VK_DYNAMIC_STATE_VIEWPORT = new VkDynamicState(0);
    public static final VkDynamicState VK_DYNAMIC_STATE_VIEWPORT_COARSE_SAMPLE_ORDER_NV = new VkDynamicState(1000164006);
    public static final VkDynamicState VK_DYNAMIC_STATE_VIEWPORT_SHADING_RATE_PALETTE_NV = new VkDynamicState(1000164004);
    public static final VkDynamicState VK_DYNAMIC_STATE_VIEWPORT_SWIZZLE_NV = new VkDynamicState(1000455024);
    public static final VkDynamicState VK_DYNAMIC_STATE_VIEWPORT_WITH_COUNT = new VkDynamicState(1000267003);
    public static final VkDynamicState VK_DYNAMIC_STATE_VIEWPORT_WITH_COUNT_EXT = VK_DYNAMIC_STATE_VIEWPORT_WITH_COUNT;
    public static final VkDynamicState VK_DYNAMIC_STATE_VIEWPORT_W_SCALING_ENABLE_NV = new VkDynamicState(1000455023);
    public static final VkDynamicState VK_DYNAMIC_STATE_VIEWPORT_W_SCALING_NV = new VkDynamicState(1000087000);

    public static VkDynamicState fromValue(int value) {
        return switch (value) {
            case 1000455007 -> VK_DYNAMIC_STATE_ALPHA_TO_COVERAGE_ENABLE_EXT;
            case 1000455008 -> VK_DYNAMIC_STATE_ALPHA_TO_ONE_ENABLE_EXT;
            case 1000524000 -> VK_DYNAMIC_STATE_ATTACHMENT_FEEDBACK_LOOP_ENABLE_EXT;
            case 4 -> VK_DYNAMIC_STATE_BLEND_CONSTANTS;
            case 1000455018 -> VK_DYNAMIC_STATE_COLOR_BLEND_ADVANCED_EXT;
            case 1000455010 -> VK_DYNAMIC_STATE_COLOR_BLEND_ENABLE_EXT;
            case 1000455011 -> VK_DYNAMIC_STATE_COLOR_BLEND_EQUATION_EXT;
            case 1000381000 -> VK_DYNAMIC_STATE_COLOR_WRITE_ENABLE_EXT;
            case 1000455012 -> VK_DYNAMIC_STATE_COLOR_WRITE_MASK_EXT;
            case 1000455014 -> VK_DYNAMIC_STATE_CONSERVATIVE_RASTERIZATION_MODE_EXT;
            case 1000455027 -> VK_DYNAMIC_STATE_COVERAGE_MODULATION_MODE_NV;
            case 1000455028 -> VK_DYNAMIC_STATE_COVERAGE_MODULATION_TABLE_ENABLE_NV;
            case 1000455029 -> VK_DYNAMIC_STATE_COVERAGE_MODULATION_TABLE_NV;
            case 1000455032 -> VK_DYNAMIC_STATE_COVERAGE_REDUCTION_MODE_NV;
            case 1000455025 -> VK_DYNAMIC_STATE_COVERAGE_TO_COLOR_ENABLE_NV;
            case 1000455026 -> VK_DYNAMIC_STATE_COVERAGE_TO_COLOR_LOCATION_NV;
            case 1000267000 -> VK_DYNAMIC_STATE_CULL_MODE;
            case 3 -> VK_DYNAMIC_STATE_DEPTH_BIAS;
            case 1000377002 -> VK_DYNAMIC_STATE_DEPTH_BIAS_ENABLE;
            case 5 -> VK_DYNAMIC_STATE_DEPTH_BOUNDS;
            case 1000267009 -> VK_DYNAMIC_STATE_DEPTH_BOUNDS_TEST_ENABLE;
            case 1000455003 -> VK_DYNAMIC_STATE_DEPTH_CLAMP_ENABLE_EXT;
            case 1000582000 -> VK_DYNAMIC_STATE_DEPTH_CLAMP_RANGE_EXT;
            case 1000455016 -> VK_DYNAMIC_STATE_DEPTH_CLIP_ENABLE_EXT;
            case 1000455022 -> VK_DYNAMIC_STATE_DEPTH_CLIP_NEGATIVE_ONE_TO_ONE_EXT;
            case 1000267008 -> VK_DYNAMIC_STATE_DEPTH_COMPARE_OP;
            case 1000267006 -> VK_DYNAMIC_STATE_DEPTH_TEST_ENABLE;
            case 1000267007 -> VK_DYNAMIC_STATE_DEPTH_WRITE_ENABLE;
            case 1000099001 -> VK_DYNAMIC_STATE_DISCARD_RECTANGLE_ENABLE_EXT;
            case 1000099000 -> VK_DYNAMIC_STATE_DISCARD_RECTANGLE_EXT;
            case 1000099002 -> VK_DYNAMIC_STATE_DISCARD_RECTANGLE_MODE_EXT;
            case 1000205000 -> VK_DYNAMIC_STATE_EXCLUSIVE_SCISSOR_ENABLE_NV;
            case 1000205001 -> VK_DYNAMIC_STATE_EXCLUSIVE_SCISSOR_NV;
            case 1000455015 -> VK_DYNAMIC_STATE_EXTRA_PRIMITIVE_OVERESTIMATION_SIZE_EXT;
            case 1000226000 -> VK_DYNAMIC_STATE_FRAGMENT_SHADING_RATE_KHR;
            case 1000267001 -> VK_DYNAMIC_STATE_FRONT_FACE;
            case 1000455020 -> VK_DYNAMIC_STATE_LINE_RASTERIZATION_MODE_EXT;
            case 1000259000 -> VK_DYNAMIC_STATE_LINE_STIPPLE;
            case 1000455021 -> VK_DYNAMIC_STATE_LINE_STIPPLE_ENABLE_EXT;
            case 2 -> VK_DYNAMIC_STATE_LINE_WIDTH;
            case 1000455009 -> VK_DYNAMIC_STATE_LOGIC_OP_ENABLE_EXT;
            case 1000377003 -> VK_DYNAMIC_STATE_LOGIC_OP_EXT;
            case 2147483647 -> VK_DYNAMIC_STATE_MAX_ENUM;
            case 1000377000 -> VK_DYNAMIC_STATE_PATCH_CONTROL_POINTS_EXT;
            case 1000455004 -> VK_DYNAMIC_STATE_POLYGON_MODE_EXT;
            case 1000377004 -> VK_DYNAMIC_STATE_PRIMITIVE_RESTART_ENABLE;
            case 1000267002 -> VK_DYNAMIC_STATE_PRIMITIVE_TOPOLOGY;
            case 1000455019 -> VK_DYNAMIC_STATE_PROVOKING_VERTEX_MODE_EXT;
            case 1000455005 -> VK_DYNAMIC_STATE_RASTERIZATION_SAMPLES_EXT;
            case 1000455013 -> VK_DYNAMIC_STATE_RASTERIZATION_STREAM_EXT;
            case 1000377001 -> VK_DYNAMIC_STATE_RASTERIZER_DISCARD_ENABLE;
            case 1000347000 -> VK_DYNAMIC_STATE_RAY_TRACING_PIPELINE_STACK_SIZE_KHR;
            case 1000455031 -> VK_DYNAMIC_STATE_REPRESENTATIVE_FRAGMENT_TEST_ENABLE_NV;
            case 1000455017 -> VK_DYNAMIC_STATE_SAMPLE_LOCATIONS_ENABLE_EXT;
            case 1000143000 -> VK_DYNAMIC_STATE_SAMPLE_LOCATIONS_EXT;
            case 1000455006 -> VK_DYNAMIC_STATE_SAMPLE_MASK_EXT;
            case 1 -> VK_DYNAMIC_STATE_SCISSOR;
            case 1000267004 -> VK_DYNAMIC_STATE_SCISSOR_WITH_COUNT;
            case 1000455030 -> VK_DYNAMIC_STATE_SHADING_RATE_IMAGE_ENABLE_NV;
            case 6 -> VK_DYNAMIC_STATE_STENCIL_COMPARE_MASK;
            case 1000267011 -> VK_DYNAMIC_STATE_STENCIL_OP;
            case 8 -> VK_DYNAMIC_STATE_STENCIL_REFERENCE;
            case 1000267010 -> VK_DYNAMIC_STATE_STENCIL_TEST_ENABLE;
            case 7 -> VK_DYNAMIC_STATE_STENCIL_WRITE_MASK;
            case 1000455002 -> VK_DYNAMIC_STATE_TESSELLATION_DOMAIN_ORIGIN_EXT;
            case 1000267005 -> VK_DYNAMIC_STATE_VERTEX_INPUT_BINDING_STRIDE;
            case 1000352000 -> VK_DYNAMIC_STATE_VERTEX_INPUT_EXT;
            case 0 -> VK_DYNAMIC_STATE_VIEWPORT;
            case 1000164006 -> VK_DYNAMIC_STATE_VIEWPORT_COARSE_SAMPLE_ORDER_NV;
            case 1000164004 -> VK_DYNAMIC_STATE_VIEWPORT_SHADING_RATE_PALETTE_NV;
            case 1000455024 -> VK_DYNAMIC_STATE_VIEWPORT_SWIZZLE_NV;
            case 1000267003 -> VK_DYNAMIC_STATE_VIEWPORT_WITH_COUNT;
            case 1000455023 -> VK_DYNAMIC_STATE_VIEWPORT_W_SCALING_ENABLE_NV;
            case 1000087000 -> VK_DYNAMIC_STATE_VIEWPORT_W_SCALING_NV;
            default -> new VkDynamicState(value);
        };
    }

    private static boolean hasVendorSuffix(String name) {
        return name.endsWith("_KHR") || name.endsWith("_EXT") || name.endsWith("_NV") || 
               name.endsWith("_AMD") || name.endsWith("_INTEL") || name.endsWith("_ARM");
    }
}
